# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CheckNameAvailabilityOutput(Model):
    """The response body for CheckNameAvailability API.

    :param name_available: Specifies if the name is available.
    :type name_available: bool
    :param reason: Specifies the reason if the name is not available. Possible
     values include: 'None', 'Invalid', 'AlreadyExists'
    :type reason: str or :class:`EntityNameUnavailabilityReason
     <microsoft.azure.management.media.models.EntityNameUnavailabilityReason>`
    :param message: Specifies the detailed reason if the name is not
     available.
    :type message: str
    """

    _attribute_map = {
        'name_available': {'key': 'NameAvailable', 'type': 'bool'},
        'reason': {'key': 'Reason', 'type': 'EntityNameUnavailabilityReason'},
        'message': {'key': 'Message', 'type': 'str'},
    }

    def __init__(self, name_available=None, reason=None, message=None):
        self.name_available = name_available
        self.reason = reason
        self.message = message
