# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegenerateKeyInput(Model):
    """The request body for a RegenerateKey API.

    :param key_type: The keyType indicating which key you want to regenerate,
     Primary or Secondary. Possible values include: 'Primary', 'Secondary'
    :type key_type: str or :class:`KeyType
     <microsoft.azure.management.media.models.KeyType>`
    """

    _validation = {
        'key_type': {'required': True},
    }

    _attribute_map = {
        'key_type': {'key': 'keyType', 'type': 'KeyType'},
    }

    def __init__(self, key_type):
        self.key_type = key_type
